[2024-11-01T06:22:32.998+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T06:22:33.012+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: self-tutorial-dag.creating_table manual__2024-11-01T06:22:31.654136+00:00 [queued]>
[2024-11-01T06:22:33.018+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: self-tutorial-dag.creating_table manual__2024-11-01T06:22:31.654136+00:00 [queued]>
[2024-11-01T06:22:33.019+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-01T06:22:33.030+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): creating_table> on 2024-11-01 06:22:31.654136+00:00
[2024-11-01T06:22:33.037+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2744) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-01T06:22:33.038+0000] {standard_task_runner.py:72} INFO - Started process 2745 to run task
[2024-11-01T06:22:33.038+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'self-tutorial-dag', 'creating_table', 'manual__2024-11-01T06:22:31.654136+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/self-tutorial-dag.py', '--cfg-path', '/tmp/tmpm9gvjx84']
[2024-11-01T06:22:33.039+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask creating_table
[2024-11-01T06:22:33.074+0000] {task_command.py:467} INFO - Running <TaskInstance: self-tutorial-dag.creating_table manual__2024-11-01T06:22:31.654136+00:00 [running]> on host 2839f63d218a
[2024-11-01T06:22:33.142+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='self-tutorial-dag' AIRFLOW_CTX_TASK_ID='creating_table' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T06:22:31.654136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T06:22:31.654136+00:00'
[2024-11-01T06:22:33.143+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T06:22:33.159+0000] {sql.py:266} INFO - Executing: 
            create table if not exists naver_search_result(
                title TEXT,
                address TEXT,
                category TEXT,
                description TEXT,
                link TEXT
            )
        
[2024-11-01T06:22:33.166+0000] {base.py:84} INFO - Retrieving connection 'db_postgres'
[2024-11-01T06:22:33.176+0000] {base.py:84} INFO - Retrieving connection 'db_postgres'
[2024-11-01T06:22:33.179+0000] {sql.py:509} INFO - Running statement: 
            create table if not exists naver_search_result(
                title TEXT,
                address TEXT,
                category TEXT,
                description TEXT,
                link TEXT
            )
        , parameters: None
[2024-11-01T06:22:33.189+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T06:22:33.189+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=self-tutorial-dag, task_id=creating_table, run_id=manual__2024-11-01T06:22:31.654136+00:00, execution_date=20241101T062231, start_date=20241101T062233, end_date=20241101T062233
[2024-11-01T06:22:33.213+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-01T06:22:33.241+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-01T06:22:33.244+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
